module.exports = [
	{
		"name": "Cape Jellison Cottage",
		"address": "",
		"contact": "Lisa",
		"sleeps": 6,
		"email": "thetripps1987@gmail.com",
		"phone": "207-223-8805",
		"website": "http://www.vacationhomerentals.com/Stockton-Springs/proID-67831/",
		"location": "44.479592,-68.836278",
		"polyline": "slnnGzqccLkGbBu@Xm@^UN{@|@_DdEMTGTA^@^XbA|E`MvB|FVhAh@lCp@vC@`@GXOPu@VuBR_CLm@Hq@Ps@h@kI~HsAnAgAp@yK|JeVjUwEgLoAeEk@yAe@m@}AiA?}ICmCGwASgC]eC_@mBwH_\\_Jq_@gBsFgAqCaBiDaIgO_Rq]eMyUiH{MsB}DRYb@aEPkBBs@DmBFuJAsRrBQlJk@~HGhBMvAKvHjBz@HlBCn@Ep@?fCd@"
	},
	{
		"name": "Compass Rose Cottage",
		"address": "",
		"contact": "",
		"sleeps": 5,
		"email": "mainecottages@hotmail.com",
		"phone": "1-800-930-2561",
		"website": "http://www.onthewaterinmaine.com/vacation-rental-home.asp?PageDataID=45035",
		"location": "44.498797,-68.808704",
		"polyline": "sdrnGre~bL^N`@V\\f@F\\BZGZITKJi@VyAZfCd@"
	},
	{
		"name": "157 Lighthouse Rd",
		"address": "",
		"contact": "Susie",
		"sleeps": 6,
		"email": "sbodymind@aol.com",
		"phone": "207-975-2528",
		"website": "",
		"location": "44.4643627,-68.8148861",
		"polyline": "ozknGzq_cL^jCh@zGjAbOP`BfAdFThCb@`NRzF?zDI~EUfEW~FKn@o@CwCv@cPpE_FtAyC~@eInCsBj@sCl@wE`A{E~@yCp@cKnCcMhDu@Xm@^UN{@|@_DdEMTGTA^@^XbA|E`MvB|FVhAh@lCp@vC@`@GXOPu@VuBR_CLm@Hq@Ps@h@kI~HsAnAgAp@yK|JeVjUwEgLoAeEk@yAe@m@}AiA?}ICmCGwASgC]eC_@mB}Pkt@yAeGgBsFgAqCaBiD_Q}[qa@qv@sB}DRYb@aEPkBBs@DmBFuJAoM?cDrBQlJk@~HGhBMvAKvHjBz@HlBCn@Ep@?fCd@"
	},
	{
		"name": "Chateau Mer",
		"address": "",
		"contact": "Barbara",
		"sleeps": 23,
		"email": "bbridges@bemidjistate.edu",
		"phone": "612-845-0416",
		"website": "https://www.homeaway.com/vacation-rental/p112188",
		"location": "44.506930,-68.809950",
		"polyline": "iwsnG`m~bLjBOlJk@~HGhBMvAKvHjBz@HlBCn@Ep@?fCd@"
	},
	{
		"name": "Davis Cottage",
		"address": "",
		"contact": "Gail",
		"sleeps": 12,
		"email": "Gadg66@gmail.com",
		"phone": "321-576-5886",
		"website": "",
		"location": "",
		"polyline": ""
	},
	{
		"name": "Fort Point Cove Cottage",
		"address": "",
		"contact": "Darlene",
		"sleeps": 8,
		"email": "bnbcove@comcast.net",
		"phone": "215-680-8155",
		"website": "https://www.homeaway.com/vacation-rental/p3494755",
		"location": "44.487523,-68.838628",
		"polyline": "}}onGj`dcLR`@{BhBgPzNsEjE{D`Ey@f@cC|A}AsG}Kue@uB{IuAgF_BiEcBwDq@qAoS_`@ab@mw@RYPyAb@sEJgFDoHAwIBwECcAr@GvHi@tBK~HG`EYvHjB`@FfCA`BEfCd@"
	},
	{
		"name": "Hersey Retreat Cottage",
		"address": "",
		"contact": "Maura",
		"sleeps": 10,
		"email": "megammans@gmail.com",
		"phone": "207-512-6402",
		"website": "http://herseyretreatcottage.com/",
		"location": "44.498991,-68.809954",
		"polyline": "uernGhm~bLSDfCd@"
	},
	{
		"name": "Moose Crossing",
		"address": "",
		"contact": "Connie",
		"sleeps": 8,
		"email": "conniekain@comcast.net",
		"phone": "774-208-2421",
		"website": "",
		"location": "",
		"polyline": ""
	},
	{
		"name": "The Belfast Beach House",
		"address": "",
		"contact": "Jeff",
		"sleeps": 6,
		"email": "belfastbeachhouse@comcast.net",
		"phone": "207-358-9198",
		"website": "https://www.homeaway.com/vacation-rental/p362659",
		"location": "44.42695,-68.9681007",
		"polyline": "sidnGzr}cLGGKAkABi@JOL}A`@c@P[VMTwAT}@_L_B_SyAsQ]{C_A_Gk@qCoAaFeBmGuA}FoA}Ge@}CaAeIm@{Hm@kI{@iIwAoJg@wCg@sBc@aBkAmD_A_CeCgFaBwBs@u@aBsAqAu@q@[wA}@_O{IcAm@aBw@qCmAeD_AeH}A{MsCcCs@sDwAmCkAeDkAwEoA}@QkBWsCYg@K_AYqAo@mA_Ac@i@e@u@[q@Y{@eAsEg@sCYkAe@oAq@uAiDeFkAyBe@sAe@wCMqA?m@@uAVwCVeBPw@`A_E\\iB^qBLmAZ_FJwBBs@CeAIgAKs@S}@m@mB}GuR{@sBcCkF}AsDkGwO}E}LgA{BeAgB{@gAyAuA}HaH}FeFgAiAg@q@}@wAm@oAa@eAg@}AuBsIaEuPsBaHkF{NuBsFmCqGyCkHe@iBYaB_@cDi@}DWyAg@wBa@yAq@qBgB{DiEuIgDyGgByCuCyEaAgBaAyBsAoDkCaIwA_Em@uAaAeB}F}IaE}FuAaBkSyTuCaDyAcBoAeBiBcDgAeCuB{F_@{@G_@}@kCsBcGs@gCUuAYaCOqCEWA_B@wVAiDGoBKoBYeCc@gCiB}HsOqp@uAgF_BiEcBwDq@qAoS_`@uRu^kNwWRYPyAb@sEJgFDoHAwIBwECcAr@GvHi@tBK~HG`EYvHjB`@FfCA`BEfCd@"
	},
	{
		"name": "The Cousins Cottage",
		"address": "",
		"contact": "Joe",
		"sleeps": 8,
		"email": "thecousinscottage@gmail.com",
		"phone": "808-282-9624",
		"website": "",
		"location": "",
		"polyline": ""
	},
	{
		"name": "Driftwood Cottage",
		"address": "",
		"contact": "",
		"sleeps": 4,
		"email": "",
		"phone": "1-800-930-2561",
		"website": "http://www.onthewaterinmaine.com/vacation-rental-home.asp?PageDataID=23615",
		"location": "44.499833,-68.810066",
		"polyline": "}jrnGvm~bL`BGp@?fCd@"
	},
	{
		"name": "Alden House",
		"address": "",
		"contact": "Rose",
		"sleeps": 0,
		"email": "aldenhouse@me.com",
		"phone": "207-338-2151",
		"website": "thealdenhouse.com",
		"location": "44.423012,-69.003746",
		"polyline": "yjcnGlhddLgS|\\kCfE{@tAsCjFsBzDmAdB}@~@qE|DaEpDgA`ASa@s@iBo@}AUOQcAEWIMm@{CiFe\\k@qE@KMgAQ{BIwB?mAPuEDs@AWVoD`BuTlAwOr@uGz@eGlAaGjA{E~@iDpAyDbAmCjCuGfDgIf@{Ah@aCRiANwAJkBBcB?eBM{Cs@gLgAgRaAcP_@cIg@_I}@_L_B_SyAsQ]{C_A_Gk@qCoAaFeBmGuA}FoA}Ge@}CaAeIm@{Hm@kI{@iIwAoJg@wCg@sBc@aBkAmD_A_CeCgFaBwBs@u@aBsAqAu@q@[wA}@_O{IcAm@aBw@qCmAeD_AeH}A{MsCcCs@sDwAmCkAeDkAwEoA}@QkBWsCYg@K_AYqAo@mA_Ac@i@e@u@[q@Y{@eAsEg@sCYkAe@oAq@uAiDeFkAyBe@sAe@wCMqA?m@@uAVwCVeBPw@`A_E\\iB^qBLmAZ_FJwBBs@CeAIgAKs@S}@m@mB}GuR{@sBcCkF}AsDkGwO}E}LgA{BeAgB{@gAyAuA}HaH}FeFgAiAg@q@}@wAm@oAa@eAg@}AuBsIaEuPsBaHkF{NuBsFmCqGyCkHe@iBYaB_@cDi@}DWyAg@wBa@yAq@qBgB{DiEuIgDyGgByCuCyEaAgBaAyBsAoDkCaIwA_Em@uAaAeB}F}IaE}FuAaBkSyTuCaDyAcBoAeBiBcDgAeCuB{F_@{@G_@}@kCsBcGs@gCUuAYaCOqCEWA_B@wVAiDGoBKoBYeCc@gCiB}HsOqp@uAgF_BiEcBwDq@qAoS_`@ab@mw@RYPyAb@sEJgFDoHAwIBwECcAr@GvHi@tBK~HG`EYvHjB`@FfCA`BEfCd@"
	},
	{
		"name": "Belfast Bay Inn & Suites",
		"address": "",
		"contact": "Ed",
		"sleeps": 0,
		"email": "info@belfastbayinn.com",
		"phone": "207-338-5600",
		"website": "belfastbayinn.com",
		"location": "44.426486,-69.006007",
		"polyline": "i`dnGntddLLBd@^x@p@q@`CyC`MaA~DsCjFsBzDmAdB}@~@qE|DaEpDgA`ASa@s@iBo@}AUOQcAEWIMm@{CiFe\\k@qE@KMgAQ{BIwB?mAPuEDs@AWVoD`BuTlAwOr@uGz@eGlAaGjA{E~@iDpAyDbAmCjCuGfDgIf@{Ah@aCRiANwAJkBBcB?eBM{Cs@gLgAgRaAcP_@cIg@_I}@_L_B_SyAsQ]{C_A_Gk@qCoAaFeBmGuA}FoA}Ge@}CaAeIm@{Hm@kI{@iIwAoJg@wCg@sBc@aBkAmD_A_CeCgFaBwBs@u@aBsAqAu@q@[wA}@_O{IcAm@aBw@qCmAeD_AeH}A{MsCcCs@sDwAmCkAeDkAwEoA}@QkBWsCYg@K_AYqAo@mA_Ac@i@e@u@[q@Y{@eAsEg@sCYkAe@oAq@uAiDeFkAyBe@sAe@wCMqA?m@@uAVwCVeBPw@`A_E\\iB^qBLmAZ_FJwBBs@CeAIgAKs@S}@m@mB}GuR{@sBcCkF}AsDkGwO}E}LgA{BeAgB{@gAyAuA}HaH}FeFgAiAg@q@}@wAm@oAa@eAg@}AuBsIaEuPsBaHkF{NuBsFmCqGyCkHe@iBYaB_@cDi@}DWyAg@wBa@yAq@qBgB{DiEuIgDyGgByCuCyEaAgBaAyBsAoDkCaIwA_Em@uAaAeB}F}IaE}FuAaBkSyTuCaDyAcBoAeBiBcDgAeCuB{F_@{@G_@}@kCsBcGs@gCUuAYaCOqCEWA_B@wVAiDGoBKoBYeCc@gCiB}HsOqp@uAgF_BiEcBwDq@qAoS_`@uRu^kNwWRYPyAb@sEJgFDoHAwIBwECcAr@GvHi@tBK~HG`EYvHjB`@FfCA`BEfCd@"
	},
	{
		"name": "Belfast Harbor Inn",
		"address": "",
		"contact": "",
		"sleeps": 0,
		"email": "stay@belfastharborinn.com",
		"phone": "207.338.2740",
		"website": "belfastharborinn.com",
		"location": "44.431219,-68.989746",
		"polyline": "q~dnGnpadLxA_EvFgNz@uBf@{Ah@aCRiANwAJkBBcB?eBM{Cs@gLgAgRaAcP_@cIg@_IaBgSuCk^]{C_A_Gk@qCoAaFeBmGuA}FoA}Ge@}CaAeIKeAoAaQ{@iIwAoJg@wCg@sBc@aBkAmD_A_CeCgFaBwBs@u@aBsAqAu@q@[wA}@_O{IcAm@aBw@qCmAeD_AiNyCwGwAcCs@sDwAmCkAeDkAq@SeD{@}@QkBWsCYg@K_AYo@Wa@WmA_Au@aAo@oAY{@[wAi@{Bg@sCYkAe@oAq@uAqAoBwAuBkAyBe@sASkAQkAMqA?{AHgBZmC\\gB`A_E\\iB^qBLmANmBT{DDaBCeAIgA_@qBm@mBcEkLyAiE{@sBcCkF}AsDiNu]gA{BeAgB{@gAyAuA{PgOgAiAg@q@}@wAm@oAa@eA{@sCcHsYsBaHcC{GgB_FuBsFmCqGyCkHe@iBYaBiAaJWyAg@wBa@yAq@qBgB{DiEuIgDyGgByCuCyEaAgBaAyBsAoDkCaIwA_Em@uAaAeB}F}IaE}FwEmF_ToU_CsCi@u@iBcDgAeC}@_Cw@{B_@{@G_@}@kCsBcGs@gCUuAYaCOqCEWA_B@wVAiDGoBKoBYeCc@gCgOso@uB{IuAgF_BiEcBwDuO}YsRq^kJiQmHeNRYPyAb@sEFsBBsBDoHAwIBwECcAr@GvHi@tBK~HG`EYvHjB`@FfCA`BEfCd@"
	},
	{
		"name": "Captain A.V. Nickels Inn",
		"address": "",
		"contact": "Brenda",
		"sleeps": 0,
		"email": "brendajliston@gmail.com",
		"phone": "207-548-1104",
		"website": "captainnickelsinn.com",
		"location": "44.458649,-68.914526",
		"polyline": "kijnGrzrcLmD}J}@cCaBsDmBaEiNu]wAeDu@yAiAaBsAyAwOeNkBeB{@cAoAmBcAyB{@oCyEcS{CgLcCaH}E_NwGwOmAeDc@uBaA}H_@_Ci@iCeAoDkAwCeAyB_JoQ}FsJ_B}CkAqCeFmO_A_Cq@uAoDyFiEmGmBoCkAuAa@c@eUwVcCqCi@q@k@w@kAmB_BcDo@_BgB_FWi@CUo@iBmAgD{AcF[yAUwAc@{FAw\\CmCGwASgC]eC_@mBwH_\\_Jq_@gBsFgAqCaBiDaIgO_Rq]eMyUiH{MsB}DRYb@aEPkBBs@DmBFuJAsRrBQlJk@~HGhBMvAKvHjBz@HlBCn@Ep@?fCd@"
	},
	{
		"name": "Camden Harbour Inn",
		"address": "",
		"contact": "Oscar",
		"sleeps": 0,
		"email": "stay@camdenharbourinn.com",
		"phone": "207-236-4200",
		"website": "camdenharbourinn.com",
		"location": "44.206027,-69.061250",
		"polyline": "s~xlG|oodLaCdBaGtFaB|A_GtFIb@OGKAe@?{DFmDH]Uk@{@cR}ZwEiFmSkU}F_KmAcB{AwAuBoA{IcCsHcDaGaDsH}FoEyC{BkA{P}FmGcC_F{C{DsC}@mA}CeHwDsIoB}C_DmD}CcCwEuBqK_EgPgFyKmF{HqF{GyFkG}EuFgFqMgOyGcKcF}GeIgIsCiC_GkEoDyB}DaAyCs@aCgAoCiBaG}DwEcC{J{EgCiBkDwCsHgE}RgL{O}IkHcBsFK}HDkD^uEH_L{@sOwAoPi@cE[oB_@iCgAcC{AuAyAy@{AiB}EsA}Fe@}EeBqWmAuHiAoEcD{JeCcJyA}Gw@mFUgDUiZSsJi@aF_AcEeAoCgCmFcB}B}BoB}IsFeFcD_GkE_JyIcIcIaBqAuDeBqW}FoCu@mB{@kB}AqA{AqAyB{AcEyBoFqBmCeM}KyGaEcZaPoFwAsEy@aBM}CHwBb@}Bz@_BbAeCdCcBpCcGrMmEhIeT|]mBzBsCjBcCt@{APiCAwEa@cJmA{H{AyO_EaDs@{DCwB^sAd@aDvBuA~A}AlCaLfTcDlFiAvAiDdDuHfFs_@|ViV~OqEtBeCp@iBZsOzAuZxC_HrA}EbBwDlBgTjM}LtGgCp@sBFyB[_Bq@oCkBeDoC}C{BoCsAiLcDiC[qCJ{@L{@TsD`ByQzIcTnKuB~AwBzBmBjC}AnC{ApDkAzDmClOkFn]uAzHoChReBxLgAlGaB|GkBxFqCnGaClEkCvDgD~C}A~AaEvCU^kAf@_H~BkKvBaMfBaDFqDUuBa@eDcByCyBuDgE_CcEcCuGcAgEcAoGkAcHeA}EiFo\\}@oJGsCVoHv@yLbCy[vAsMhCyMtCmK|@iCbKcW~@aEb@gEDeEa@cJcFa|@iFqp@_B{NiBsImEoPwBgLcBsN{@qLi@eGyAkLiCwMwBwG}DeIwDcEoDuB{SgMcHyCe]{HuPoG_FmA}G{@eCs@eAk@gBkBk@aAw@eCaAwEgAuEmBsDaEmG}@yCa@}CEeB^sFrCaNb@mDZ_FFiBC{B]cCoBeGeG{PoEuJiNu]mC_G}C{DwOeNgDiDsCgF{@oCyEcS{CgLcCaH}E_NwGwOmAeDc@uBaA}HiAiGeAoDqCqG_JoQ}FsJkDoHeFmOqBuEyJgO{EiGsZ{\\wBeDoCcGsDiKiDkKq@qDc@{FAw\\KeFq@mGwT_`AoDeKcLqTe`@kt@iH{MsB}DRYb@aET_DLcNAsR`N}@hLUvAKvHjBz@H|CIp@?fCd@"
	},
	{
		"name": "Camden Windward House",
		"address": "",
		"contact": "Kristen",
		"sleeps": 0,
		"email": "bnb@windwardhouse.com",
		"phone": "207-236-9656",
		"website": "windwardhouse.com",
		"location": "44.212369,-69.064446",
		"polyline": "gfzlGtcpdLuQkZwEiFmSkU}F_KmAcB{AwAuBoA{IcCsHcDaGaDsH}FoEyC{BkA{P}FmGcC_F{C{DsC}@mA}CeHwDsIoB}C_DmD}CcCwEuBqK_EgPgFyKmF{HqF{GyFkG}EgCuBmBqBqMgOyGcKcF}GeIgIsCiC_GkEoDyB}DaAyCs@aCgAoCiBaG}DwEcC{J{EgCiBkDwCaBgAqE_CcJiFyG}D{O}IgA[cFgAsFK}HDkD^uEH_L{@sOwAoPi@cE[oB_@iCgAcC{AuAyAy@{AiB}EsA}Fe@}EeBqWmAuHiAoEcD{Jw@aCmAaFyA}Gw@mFUgDUiZSsJi@aF_AcEeAoCgCmFcB}B}BoB}IsFeFcD_GkE_JyIcIcIaBqAuDeBqW}FoCu@mB{@kB}AqA{AqAyB{AcEaAqCw@}AqBmCeM}KyGaEcZaPoFwAsEy@aBM}CHwBb@}Bz@_BbAeCdCcBpCcGrMmEhIeT|]mBzBsCjBcCt@{APiCAwEa@cJmA{H{AyO_EaDs@aBGyABwB^sAd@eBbA{@r@uA~A}AlCaLfTcDlFiAvAiDdDuHfFs_@|ViV~OqEtBeCp@iBZsOzAuZxCuEv@iAZ}EbBwDlBgTjM}LtGgCp@sBFyB[_Bq@oCkBeDoC}C{BoCsAiLcDiC[qCJ{@L{@TsD`ByQzIcTnKuB~AwBzBmBjC}AnC{ApDkAzDaAbFkAhHkFn]uAzHoChReBxLgAlGaB|GkBxFqCnGaClEkCvDgD~C}A~AaEvCU^kAf@_H~BkKvBaMfBaDFqDUuBa@eDcByCyBuDgE_CcEcCuGcAgEcAoGkAcHeA}EiFo\\}@oJGsCVoHv@yLbCy[vAsMhCyMtCmK|@iCbKcW~@aEb@gEDeEa@cJcFa|@iFqp@_B{NiBsImEoPwBgLcBsN{@qLi@eGyAkLmAoH{@gDwBwG}DeIwDcEoDuB{SgMcHyCe]{HuPoG_FmA}G{@eCs@eAk@gBkBk@aAw@eCaAwEgAuEmBsDaEmG}@yCa@}CEeB^sFrCaNb@mDZ_FFiBC{B]cCoBeGeG{PoEuJiNu]mC_G}C{DwOeNgDiDsCgF{@oCyEcS{CgLcCaH}E_NwGwOmAeDc@uBaA}HiAiGeAoDqCqG_JoQ}FsJkDoHeFmOqBuEyJgO{EiGsZ{\\wBeDoCcGsDiKiDkKq@qDc@{FAw\\KeFq@mGwT_`AgBsFgAqCcLqTe`@kt@iH{MsB}DRYb@aET_DLcNAsR`N}@hLUvAKvHjBz@H|CIp@?fCd@"
	},
	{
		"name": "Comfort Inn",
		"address": "",
		"contact": "Barry",
		"sleeps": 0,
		"email": "stay@comfortinnbelfast.com",
		"phone": "207-338-2090",
		"website": "belfastmainehotel.com",
		"location": "44.429230,-68.976894",
		"polyline": "wqdnGr`_dLaByXOqDYiEo@aJsAaPeBmTi@iGu@qFw@_Eq@sCgA{DeCsJsA{GwAsJo@kGKkAo@eJi@eGyAkLmAoH{@gD_AaDw@uBgAeCuB_EgByBoAiA_BgAoAm@kKqGoGuDoDcBsBu@yFuAkPoD_Du@{CeAsB}@cFqBwBm@iDy@uAUgEe@eAU_Bq@e@WmAkAk@y@Yg@Ys@]qAg@uB_AcFa@sAm@sA_A_B_AyAaAsA_A_B[w@a@aBQeAOwAEy@?uAP_CXwBxAqGdAcGX{DRmD@kBC{@MiAOy@YcA}GyR}@cCaBsDmBaEcAgCeLmYwAeDu@yAiAaBsAyAoFyEgHkGkBeB{@cAoAmBcAyBg@}AmBwH_C}J{CgLcCaHaBsE{BkGqC{GeC{FmAeDc@uB]aCc@{D_@_Ci@iC]qAg@}AkAwCeLiU}FsJ_B}CkAqCcAwCaDuJ_A_Cq@uAoDyFiEmGmBoCkAuAa@c@aL_MgLiMuAiBkAmB_BcDo@_BaAmCe@qAWi@CUo@iBmAgD{AcF[yAUwAWgDKsAAyQ?}ICmCGwASgC]eC_@mB}Pkt@yAeGgBsFgAqCaBiD_Q}[qa@qv@sB}DRYb@aEPkBBs@DmBFuJAoM?cDrBQlJk@~HGhBMvAKvHjBz@HlBCn@Ep@?fCd@"
	},
	{
		"name": "Four Points Sheraton",
		"address": "",
		"contact": "Bernadette",
		"sleeps": 0,
		"email": "bernadette.whitcomb@fourpointsbangor.com",
		"phone": "207-947-6721",
		"website": "fourpointsbangorairport.com",
		"location": "44.809210,-68.813965",
		"polyline": "qxnpGff_cLiAS_@RwAhB}@Xs@?mN}Fu@a@AQDaBBkBIoBuBmH_@eEX_Fp@cClDeJ`B}Dd@u@fAa@hBKv@@nBE`@@`DbCd@Bt@v@xIbI|@|@tClBrOpJnDd@hFm@vDs@tK}AdB]hD}BrAgAfA_@`AG`AHjA`@x@p@jJfKfBx@~DZbCd@tJtFnHhEpAt@VPFmAnAyWd@mJdBq\\TgLc@uNyEq{@OcFHwFt@oHvBeIfFaQxCwMl@cEjAmMf@qFb@gBFYVu@v@_AbAQv@Xf@t@TnACvAmAdEYt@zAvAx@f@jBxAjNnKdQ`LzBdA~FnB`JfCxAZ`Ji@bAAf@b@rArE~CpFdBdCzAj@~ADjHA`APlFbCjCpBnAdBzBtEdDlG~EtGrG`GxFtE`FfEjBrBfDnGzFxS|J~XhDfIrE~IbDbEhChBpAd@dJxBzB|@vBpAzJlJ|BxCtAtDjBfKhAjGb@pA~FxJvGpK|BbC|FtDfHrFdEdFdGhIpD`ErE~DlBx@zETbY}ArE_A~C}@rEo@rGRvFl@~Bh@jHpAbIj@`ESzFmA|GcB~FiBze@uPtLkEjKmDtMgFvBiBbAcB|BaHjD{JzC_GvDeFjD_DrCoBdEgBrFmA|BOxDJnI^bCIjEe@bHkA`CgAzAiA|GmF~F}C|C{BdIgK|EcEtDgCzDsA~Da@~Ql@fD`@|CjAjJdFbCpB`CrC~AdCtDbJvGxQjCbE~QhPnA|@jFfCpIfF|ErDrCvEzDhHtEtE~LzLfEnDdD|@rDR~KbApPlCnH~AzYlQtLzGjKdIdAp@rDnAxCt@|BJdAEvCs@xFwAfLq@hOcBbDw@~D}AbBiAhAmAfDqFbGcK~AcBtJ{FfOaIb`@oZpUkQxX}JtL_GpEiCpBmBrGmHjCaCxCkB~EsB`D}@tCKrDRxFCfDc@dEkAdN{ErDe@xLm@rAUpCsA~DyExB}CxEaD|BuAlAsAzJ_TpFuL~AoDn@}BfBuNx@eIPkOXiHjDl@vEfBpFbDbF~BvMvE|_@dMxAt@bA~AZnB?dBa@bIkDvQuIjc@A|Bl@hC`@n@z@f@v@LjAMdBOrAHpBn@nD|ArB|AvB`CvBnBfBbA~Ah@xCZlHg@xGm@pRsBzDWdDChE\\dHpArEf@nECnTqB|YaCfH?lPpArHr@vFhApGfCjGfE`KtIvBvAlCdAvDz@|DR`Oc@~Sk@hF\\jFxA`EzB`EnDvCbEbAfBRYb@aEZmGDeY?cDrBQlJk@hLUvAKvHjBz@H|CIxDd@"
	},
	{
		"name": "Glenmoor by the Sea",
		"address": "",
		"contact": "Polly",
		"sleeps": 0,
		"email": "glenmoorbythesea@yahoo.com",
		"phone": "207-236-7905",
		"website": "glenmoorbythesea.com",
		"location": "44.259155,-69.023185",
		"polyline": "wjcmG~ahdL}I{I}CiCeGkEqBeAiEaAoDcAgCwAgD{BkG}DcFeCeHiDmIyG{I{EeJkFcT_MmAk@iAYqDy@_AMmAEcG@{EHcE^gE?gPuAiD_@qHe@aPi@gCY}A_@gCkAuCsBqAkBg@iAcAmC}@_Ds@uD_@sEiAmR_@sDkA}GwAkFoDoKkCsKmAkGa@eDSyDIiJKoRWcGo@aF_AmDgBoEiBkDkB{BeCkBcLgHwFuD_FeE_M}LaD_D_BkA_By@cCu@mVmFeCu@iB_AoBgBoA}AeBmDoA{DcAaCu@qAmB{BmM_LgOuImP_J{Ak@_H}AqDg@k@AcBBkAJoBd@iChAqA~@{@x@{AlBwBdEkFjLaFvIiSp\\uBvBwA|@qAj@yBb@aAF}CG}I}@cHgAyGyA}OcEcBWcBEyAFwBb@}Al@uA~@y@p@_BvBqPf[_B`CiCvC{BnBe_@tV_MhIcSnMkFvBeFx@uXlC}RrBeG|AiEbBkZdQ{KzF}B`@yB@mB_@aBu@wCwBwCcCoDeCaDsAwKwCy@KyAEwBLiCp@ec@xSmEzB_B`AqB`BkBvBmBpCuAfCgBvEcAlDaApFyBnNsDtUmC|PqArJ{CtRu@jDuAjFkBlFaDdHuBlDeA|A}@z@qFvFaEvCKX[NiBt@iBp@uGfByIzAwEr@{Db@}C?}CW}@QqAk@{C_B{CgCeBoBgA_BmBsDeAeCwA}E{B}Mg@uCOe@uD{TyB_OSwAKsAUeDE{CTaH`AyMdCc\\r@uGz@eGxC}MvBiH|AgEvFgNbBqE|@kEZcEBiEkEou@gAcSaBgSuCk^]{C_A_G{BsJ{DkOuB{LmAkKoAaQ{@iIwAoJoAkGc@aBkAmD_A_CeCgFaBwBuCiC{EoC_O{IeDeBqCmAeD_AiNyCwGwAcCs@aIcDwE_BcFmAgH}@oBq@oBwAu@aAo@oAu@sCqAoG_A{CcCeEwAuBkAyBy@_D_@}C?{AHgBZmC\\gB~AiH^qB\\{DZ}GMmC_@qBqFyOuC}HaF_LiNu]gA{BeAgB{@gAyAuA{PgOoB{BkBgDa@eA{@sCcHsYsBaHcC{G}EsMgH}P_AkEiAaJ_AqEsAkEqHqOoGsLwEaIuCiHcFaOoB{D_M{QwEmF_ToU_CsCsCyEeCeGwAwDeAkDsBcGs@gCo@wEOqCGwB?a\\S_F}@mGgOso@kEcQ_BiEcBwDuO}YsRq^kJiQmHeNRYPyAb@sEFsBBsBBgSBwECcAr@GvHi@tLS`EYxIrBhFGfCd@"
	},
	{
		"name": "Hartstone Inn",
		"address": "",
		"contact": "Meghan",
		"sleeps": 0,
		"email": "info@hartstoneinn.com",
		"phone": "207-236-4259",
		"website": "hartstoneinn.com",
		"location": "44.208550,-69.066438",
		"polyline": "inylG~opdLeF_Hw@YuIRo@@]QeHeLkImNoAcBqJmKaLeMaBeC{FuJiAiA{B_BeBo@yF{AsFwBiHqD}FoEyEmD}BqAmEoBmSaHuFaDaFiDu@}@sBcEsEyKuBsDsCgDaDqCoCyAyJwDaE{A}KiDuBu@iHmDaIcFkQwNaEkDkMqNsPiV}M{M}EqDkEyCeCy@{Dy@aDmAwBqAkK}GiLuFsD{BsD_DoD}B{MoHcRsKiFyCcA]wEeAaBQiM?gCXyETkLs@qKgAiPw@cJ_@aCa@gBo@mC{AqAcAqAkBkBwEyAuFi@qEq@iLq@iJaAeHgA_FcBoFcDyJoDyPm@}FMyFWo]a@yE}@{E}@mC}BiFeBoCwBuBeVsO_FeEuEsE}I_JuAkAwCcBcCu@_SiEqEiA}Ao@iBuA_BaBiAgBeBgEmBiFsB}CoLkKcDcC_^uRaEqAkJ_BoC@gC\\_Cv@_B|@kB`BiCpDkFhLoDdH}M|TgHhLw@|@uCvBqAj@yBb@qCHkLgAgLoBmOyDcFkAqAKaB?qBT{Ab@qBdAaCzB{A|BeKxRcFvIqEzE_Z`Sqc@zYoFtCgC~@sB`@mMtAqYnCeGr@aDr@_DbAqEpBiPpJmQ|JuC`AiBNeCSaBi@{BwAcJgHmBcAqKcD_Dm@yAEyAHw@Hu@ReC`AuPfIqUbLaDxByAvAiCbDaDdGcBdFcAjE_I`h@{C`RmFh^}A~GcBrFkCrG_CrEgCzDoHrHaEvCKX[NsEfBuGfBcEv@qDh@aHdAeDNuDQsB[sDeBaC}AyD_EkCgEoBqEwA}Ew@kEkBgL}@aEuGwb@g@gIPcHZ{F`BuT`CmXhCgOjCeK`H}QfDgIpA}Eb@aDNoEMaG{Bo_@aBgZeB_VwEoj@kBqKuDoNeD{OgBcNm@{Hm@kI{@iIwAoJoAkGoBoGeEgJuCmDsDiCiSuLwHsDkM}C{MsCwHkCsHwCwEoAiDi@{De@_AYqAo@qBiB{AcDgCsLwAeDiDeFkAyBe@sAe@wCM_C@uAn@}FpBaJl@_Ef@wI?yBU{BaAkD}GuR_E_JiJkUeHyPaCoD}UgTsCyEiAcDuBsIaEuPsBaHkF{NcGeOyCkHe@iBy@eGaAwGiAqEyCmHiEuIoGsLwEaIaAyB_FqNeCuG_IcMwG_JkSyT_IkJqDiHuB{FyEkNiA}Ei@sGEoZIyGe@uFmCeMsOqp@uAgF_BiEuCiGoS_`@ab@mw@RYPyAb@sEJgFF_ZCcAr@GvHi@tLS`EYxIrBfCA`BEfCd@"
	},
	{
		"name": "The Homeport Inn",
		"address": "",
		"contact": "Marcia",
		"sleeps": 0,
		"email": "marcia@homeporthistoricinn.com",
		"phone": "207-548-2259",
		"website": "homeporthistoricinn.com",
		"location": "44.458320,-68.915258",
		"polyline": "igjnGd_scLmGqQ{@sBcCkF}AsDkGwO}E}LgA{BeAgB{@gAyAuA}HaH}FeFgAiAg@q@}@wAm@oAa@eAg@}AuBsIaEuPsBaHkF{NuBsFmCqGyCkHe@iBYaB_@cDi@}DWyAg@wBa@yAq@qBgB{DiEuIgDyGgByCuCyEaAgBaAyBsAoDkCaIwA_Em@uAaAeB}F}IaE}FuAaBkSyTuCaDyAcBoAeBiBcDgAeCuB{F_@{@G_@}@kCsBcGs@gCUuAYaCOqCEWA_B@wVAiDGoBKoBYeCc@gCiB}HsOqp@uAgF_BiEcBwDq@qAoS_`@uRu^kNwWRYPyAb@sEJgFDoHAwIBwECcAr@GvHi@tBK~HG`EYvHjB`@FfCA`BEfCd@"
	},
	{
		"name": "Inn at Sunrise Point",
		"address": "",
		"contact": "Lois",
		"sleeps": 0,
		"email": "info@sunrisepoint.com",
		"phone": "207-236-7716",
		"website": "sunrisepoint.com",
		"location": "44.258831,-69.018008",
		"polyline": "uhcmGpagdLkCxIaAfCsChGwBoB}EqDkEyCeCy@{Dy@aDmAwBqAkK}GiLuFsD{BsD_DoD}B{MoHcRsKiFyCcA]wEeAaBQiM?gCXyETkBE_Im@qKgAqHe@wFQcJ_@aCa@gBo@mC{AqAcAqAkBkBwEyAuFi@qEq@iLq@iJaAeHgA_FcBoFcDyJoDyPm@}FMyFWo]a@yE}@{E}@mC}BiFeBoCwBuBeVsO_FeEuEsE}I_JuAkAwCcBcCu@_SiEqEiA}Ao@iBuA_BaBiAgBeBgEmBiFsB}CoLkKcDcC_^uRaEqAyDw@qDg@oC@gC\\_Cv@_B|@kB`B{AlBm@bAkFhLoDdH}M|TgHhLw@|@uCvBqAj@yBb@qCHkLgAgLoBmOyDcFkAqAKaB?qBT{Ab@qBdAaCzB{A|BeKxRcCtE_B`CiCvCgAbAiFrDuRlMqc@zYoFtCgC~@sB`@mMtAqYnCeGr@aDr@_DbAqEpBiPpJmQ|JkAh@iAViBNeCSaBi@{BwAcJgHmBcAqKcD_Dm@yAEyAHw@Hu@ReC`AuPfIqUbLaDxByAvAiCbDoArBqApCcBdFcAjE_I`h@{C`RqArJ{CtR}A~GcBrFkCrG_CrEgCzD}@z@qFvFaEvCKX[NsEfBuGfBcEv@qDh@aHdAeDNuDQsB[sDeBaC}AyD_EkCgEoBqEwA}Ew@kEkBgL}@aEiFe\\k@qE]oEIwBPcHZ{F`BuT`CmXz@eGlAaGjCeKpAyDnEcLfDgIpA}Eb@aDNoEMaG{Bo_@aBgZeB_VwEoj@kBqKuDoNuA}FoA}GgBcNm@{Hm@kI{@iIwAoJoAkGoBoGeEgJuCmDaBsAqAu@iSuLeDeBqCmAkM}C{MsCcCs@sDwAsHwCwEoAiDi@{De@_AYqAo@qBiBe@u@u@mBgCsLwAeDiDeFkAyBe@sAe@wCM_C@uAn@}FpBaJl@_Ef@wI?yBU{BaAkD}GuR_E_JiJkUeHyPaCoD}UgTg@q@kBgDiAcDuBsIaEuPsBaHkF{NcGeOyCkHe@iBy@eGaAwGiAqEq@qBgB{DiEuIoGsLwEaIaAyB_FqNeCuG_IcMwG_JkSyToFeGoAeBiBcDgAeCuB{FyEkNiA}Ei@sGGwB@wVIyGe@uFmCeMsOqp@uAgF_BiEuCiGoS_`@ab@mw@RYPyAb@sEJgFF_ZCcAr@GvHi@tLS`EYxIrBfCA`BEfCd@"
	},
	{
		"name": "Lord Camden Inn",
		"address": "",
		"contact": "Erick",
		"sleeps": 0,
		"email": "info@lordcamdeninn.com",
		"phone": "207-236-4325",
		"website": "lordcamdeninn.com",
		"location": "44.210100,-69.064848",
		"polyline": "cxylGffpdLyHPo@@]QeHeLkImNoAcBqJmKaLeMaBeC{FuJiAiA{B_BeBo@yF{AsFwBiHqD}FoEyEmD}BqAmEoBmSaHuFaDaFiDu@}@sBcEsEyKuBsDsCgDaDqCoCyAyJwDaE{A}KiDuBu@iHmDaIcFkQwNaEkDkMqNsPiV}M{M}EqDkEyCeCy@{Dy@aDmAwBqAkK}GiLuFsD{BsD_DoD}B{MoHcRsKiFyCcA]wEeAaBQiM?gCXyETkLs@qKgAiPw@cJ_@aCa@gBo@mC{AqAcAqAkBkBwEyAuFi@qEq@iLq@iJaAeHgA_FcBoFcDyJoDyPm@}FMyFWo]a@yE}@{E}@mC}BiFeBoCwBuBeVsO_FeEuEsE}I_JuAkAwCcBcCu@_SiEqEiA}Ao@iBuA_BaBiAgBeBgEmBiFsB}CoLkKcDcC_^uRaEqAkJ_BoC@gC\\_Cv@_B|@kB`BiCpDkFhLoDdH}M|TgHhLw@|@uCvBqAj@yBb@qCHkLgAgLoBmOyDcFkAqAKaB?qBT{Ab@qBdAaCzB{A|BeKxRcFvIqEzE_Z`Sqc@zYoFtCgC~@sB`@mMtAqYnCeGr@aDr@_DbAqEpBiPpJmQ|JuC`AiBNeCSaBi@{BwAcJgHmBcAqKcD_Dm@yAEyAHw@Hu@ReC`AuPfIqUbLaDxByAvAiCbDaDdGcBdFcAjE_I`h@{C`RmFh^}A~GcBrFkCrG_CrEgCzDoHrHaEvCKX[NsEfBuGfBcEv@qDh@aHdAeDNuDQsB[sDeBaC}AyD_EkCgEoBqEwA}Ew@kEkBgL}@aEuGwb@g@gIPcHZ{F`BuT`CmXhCgOjCeK`H}QfDgIpA}Eb@aDNoEMaG{Bo_@aBgZeB_VwEoj@kBqKuDoNeD{OgBcNm@{Hm@kI{@iIwAoJoAkGoBoGeEgJuCmDsDiCiSuLwHsDkM}C{MsCwHkCsHwCwEoAiDi@{De@_AYqAo@qBiB{AcDgCsLwAeDiDeFkAyBe@sAe@wCM_C@uAn@}FpBaJl@_Ef@wI?yBU{BaAkD}GuR_E_JiJkUeHyPaCoD}UgTsCyEiAcDuBsIaEuPsBaHkF{NcGeOyCkHe@iBy@eGaAwGiAqEyCmHiEuIoGsLwEaIaAyB_FqNeCuG_IcMwG_JkSyT_IkJqDiHuB{FyEkNiA}Ei@sGEoZIyGe@uFmCeMsOqp@uAgF_BiEuCiGoS_`@ab@mw@RYPyAb@sEJgFF_ZCcAr@GvHi@tLS`EYxIrBfCA`BEfCd@"
	},
	{
		"name": "Seascape Motel",
		"address": "",
		"contact": "Christopher",
		"sleeps": 0,
		"email": "stay@seascapemotel.com",
		"phone": "207-338-2130",
		"website": "seascapemotel.com",
		"location": "44.430148,-68.969745",
		"polyline": "awdnGxs}cLgFeo@]{C_A_Gk@qCoAaFeBmGuA}FoA}Ge@}CaAeIKeAoAaQ{@iIwAoJg@wCg@sBc@aBkAmD_A_CeCgFaBwBs@u@aBsAqAu@q@[wA}@_O{IcAm@aBw@qCmAeD_AiNyCwGwAcCs@sDwAmCkAeDkAq@SeD{@}@QkBWsCYg@K_AYo@Wa@WmA_Au@aAo@oAY{@[wAi@{Bg@sCYkAe@oAq@uAqAoBwAuBkAyBe@sASkAQkAMqA?{AHgBZmC\\gB`A_E\\iB^qBLmANmBT{DDaBCeAIgA_@qBm@mBcEkLyAiE{@sBcCkF}AsDiNu]gA{BeAgB{@gAyAuA{PgOgAiAg@q@}@wAm@oAa@eA{@sCcHsYsBaHcC{GgB_FuBsFmCqGyCkHe@iBYaBiAaJWyAg@wBa@yAq@qBgB{DiEuIgDyGgByCuCyEaAgBaAyBsAoDkCaIwA_Em@uAaAeB}F}IaE}FwEmF_ToU_CsCi@u@iBcDgAeC}@_Cw@{B_@{@G_@}@kCsBcGs@gCUuAYaCOqCEWA_B@wVAiDGoBKoBYeCc@gCgOso@uB{IuAgF_BiEcBwDuO}Y_^{p@mHeNRYPyAb@sEFsBBsBDoHAwIBwECcAr@GvHi@tBK~HG`EYvHjB`@FfCA`BEfCd@"
	},
	{
		"name": "The Jeweled Turret Inn",
		"address": "",
		"contact": "Carl",
		"sleeps": 0,
		"email": "info@jeweledturret.com",
		"phone": "207-338-2304",
		"website": "jeweledturret.com",
		"location": "44.423940,-69.004127",
		"polyline": "wpcnG~jddLsBoCaBtDi@`AgAnCWr@Ut@_AdDyC`MaA~DsCjFsBzDmAdB}@~@qE|DaEpDgA`ASa@s@iBo@}AUOQcAEWIMm@{CgC_PaBeKWyBSwA@KMgAQ{BCi@E{CPuEDs@AWVoDh@iHdCc\\r@uGz@eGlAaGjA{E~@iDv@_C|AgEvFgNz@uBf@{Ah@aCRiANwAJkBBcB?eBM{Cs@gLgAgRaAcP_@cIg@_IaBgSuCk^]{C_A_Gk@qCoAaFeBmGuA}FoA}Ge@}CaAeIKeAoAaQ{@iIwAoJg@wCg@sBc@aBkAmD_A_CeCgFaBwBs@u@aBsAqAu@q@[wA}@_O{IcAm@aBw@qCmAeD_AiNyCwGwAcCs@sDwAmCkAeDkAq@SeD{@}@QkBWsCYg@K_AYo@Wa@WmA_Au@aAo@oAY{@[wAi@{Bg@sCYkAe@oAq@uAqAoBwAuBkAyBe@sASkAQkAMqA?{AHgBZmC\\gB`A_E\\iB^qBLmANmBT{DDaBCeAIgA_@qBm@mBcEkLyAiE{@sBcCkF}AsDiNu]gA{BeAgB{@gAyAuA{PgOgAiAg@q@}@wAm@oAa@eA{@sCcHsYsBaHcC{GgB_FuBsFmCqGyCkHe@iBYaBiAaJWyAg@wBa@yAq@qBgB{DiEuIgDyGgByCuCyEaAgBaAyBsAoDkCaIwA_Em@uAaAeB}F}IaE}FwEmF_ToU_CsCi@u@iBcDgAeC}@_Cw@{B_@{@G_@}@kCsBcGs@gCUuAYaCOqCEWA_B@wVAiDGoBKoBYeCc@gCgOso@uB{IuAgF_BiEcBwDuO}Y_^{p@mHeNRYPyAb@sEFsBBsBDoHAwIBwECcAr@GvHi@tBK~HG`EYvHjB`@FfCA`BEfCd@"
	},
	{
		"name": "Whitehall Inn",
		"address": "",
		"contact": "Russ",
		"sleeps": 0,
		"email": "reservations@whitehall-inn.com",
		"phone": "207-236-3391",
		"website": "whitehall-inn.com",
		"location": "44.216552,-69.058804",
		"polyline": "i`{lGh`odLyRuT}F_KmAcB{AwAuBoA{IcCsHcDaGaDsH}FoEyC{BkA{P}FmGcC_F{C{DsC}@mA}CeHwDsIoB}C_DmD}CcCwEuBqK_EgPgFyKmF{HqF{GyFkG}EgCuBmBqBqMgOyGcKcF}GeIgIsCiC_GkEoDyB}DaAyCs@aCgAoCiBaG}DwEcC{J{EgCiBkDwCaBgAqE_CcJiFyG}D{O}IgA[cFgAsFK}HDkD^uEH_L{@sOwAoPi@cE[oB_@iCgAcC{AuAyAy@{AiB}EsA}Fe@}EeBqWmAuHiAoEcD{Jw@aCmAaFyA}Gw@mFUgDUiZSsJi@aF_AcEeAoCgCmFcB}B}BoB}IsFeFcD_GkE_JyIcIcIaBqAuDeBqW}FoCu@mB{@kB}AqA{AqAyB{AcEaAqCw@}AqBmCeM}KyGaEcZaPoFwAsEy@aBM}CHwBb@}Bz@_BbAeCdCcBpCcGrMmEhIeT|]mBzBsCjBcCt@{APiCAwEa@cJmA{H{AyO_EaDs@aBGyABwB^sAd@eBbA{@r@uA~A}AlCaLfTcDlFiAvAiDdDuHfFs_@|ViV~OqEtBeCp@iBZsOzAuZxCuEv@iAZ}EbBwDlBgTjM}LtGgCp@sBFyB[_Bq@oCkBeDoC}C{BoCsAiLcDiC[qCJ{@L{@TsD`ByQzIcTnKuB~AwBzBmBjC}AnC{ApDkAzDaAbFkAhHkFn]uAzHoChReBxLgAlGaB|GkBxFqCnGaClEkCvDgD~C}A~AaEvCU^kAf@_H~BkKvBaMfBaDFqDUuBa@eDcByCyBuDgE_CcEcCuGcAgEcAoGkAcHeA}EiFo\\}@oJGsCVoHv@yLbCy[vAsMhCyMtCmK|@iCbKcW~@aEb@gEDeEa@cJcFa|@iFqp@_B{NiBsImEoPwBgLcBsN{@qLi@eGyAkLmAoH{@gDwBwG}DeIwDcEoDuB{SgMcHyCe]{HuPoG_FmA}G{@eCs@eAk@gBkBk@aAw@eCaAwEgAuEmBsDaEmG}@yCa@}CEeB^sFrCaNb@mDZ_FFiBC{B]cCoBeGeG{PoEuJiNu]mC_G}C{DwOeNgDiDsCgF{@oCyEcS{CgLcCaH}E_NwGwOmAeDc@uBaA}HiAiGeAoDqCqG_JoQ}FsJkDoHeFmOqBuEyJgO{EiGsZ{\\wBeDoCcGsDiKiDkKq@qDc@{FAw\\KeFq@mGwT_`AgBsFgAqCcLqTe`@kt@iH{MsB}DRYb@aET_DLcNAsR`N}@hLUvAKvHjBz@H|CIp@?fCd@"
	},
	{
		"name": "Yankee Clipper Motel",
		"address": "",
		"contact": "Michael",
		"sleeps": 0,
		"email": "theskipper@yankeeclippermotelbelfast.com",
		"phone": "207-338-2353",
		"website": "yankeeclippermotelbelfast.com",
		"location": "44.433475,-68.997917",
		"polyline": "glenG~ccdLn@cIr@uGz@eGlAaGjA{E~@iDpAyDbAmCjCuGfDgIf@{Ah@aCRiANwAJkBBcB?eBM{Cs@gLgAgRaAcP_@cIg@_I}@_L_B_SyAsQ]{C_A_Gk@qCoAaFeBmGuA}FoA}Ge@}CaAeIm@{Hm@kI{@iIwAoJg@wCg@sBc@aBkAmD_A_CeCgFaBwBs@u@aBsAqAu@q@[wA}@_O{IcAm@aBw@qCmAeD_AeH}A{MsCcCs@sDwAmCkAeDkAwEoA}@QkBWsCYg@K_AYqAo@mA_Ac@i@e@u@[q@Y{@eAsEg@sCYkAe@oAq@uAiDeFkAyBe@sAe@wCMqA?m@@uAVwCVeBPw@`A_E\\iB^qBLmAZ_FJwBBs@CeAIgAKs@S}@m@mB}GuR{@sBcCkF}AsDkGwO}E}LgA{BeAgB{@gAyAuA}HaH}FeFgAiAg@q@}@wAm@oAa@eAg@}AuBsIaEuPsBaHkF{NuBsFmCqGyCkHe@iBYaB_@cDi@}DWyAg@wBa@yAq@qBgB{DiEuIgDyGgByCuCyEaAgBaAyBsAoDkCaIwA_Em@uAaAeB}F}IaE}FuAaBkSyTuCaDyAcBoAeBiBcDgAeCuB{F_@{@G_@}@kCsBcGs@gCUuAYaCOqCEWA_B@wVAiDGoBKoBYeCc@gCiB}HsOqp@uAgF_BiEcBwDq@qAoS_`@uRu^kNwWRYPyAb@sEJgFDoHAwIBwECcAr@GvHi@tBK~HG`EYvHjB`@FfCA`BEfCd@"
	}
];